stages:
  - lint
  - build

# Lint the client.
lint-client:
  stage: lint
  image: node:22
  script:
    - cd client
    - npm ci
    - npm run lint

# Build the client's production bundle.
build-client:
  stage: build
  image: node:22
  script:
    - cd client
    - npm ci
    - npm run build